### ISSUE TITLE
Segfault on Ubuntu 16.10

### ISSUE THREAD

**Issue by twdkeule** [thiezn/iperf3-python#14]
Kernel: 4.8
Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
iperf 3.1.3

Stacktrace:
ThreadStacktrace:
>  Thread 1 (Thread 0x7f2e69160700 (LWP 19792)):
>  #0  0x00007f2e65db2164 in iperf_defaults () from /usr/lib/x86_64-linux-gnu/libiperf.so.0
>  No symbol table info available.
>  #1  0x00007f2e67199a08 in ffi_call_unix64 () from /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so
>  No symbol table info available.
>  #2  0x00007f2e6719946a in ffi_call () from /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so
>  No symbol table info available.
>  #3  0x00007f2e67192c14 in _ctypes_callproc () from /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so
>  No symbol table info available.
>  #4  0x00007f2e671913c1 in ?? () from /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so
>  No symbol table info available.
>  #5  0x00005636e05f72f7 in PyObject_Call ()
>  No symbol table info available.
>  #6  0x00005636e0562f01 in PyEval_EvalFrameEx ()
>  No symbol table info available.
>  #7  0x00005636e0562b0f in PyEval_EvalFrameEx ()
>  No symbol table info available.
>  #8  0x00005636e05681ef in PyEval_EvalCodeEx ()
>  No symbol table info available.
>  #9  0x00005636e051139f in ?? ()
>  No symbol table info available.
>  #10 0x00005636e05f72f7 in PyObject_Call ()
>  No symbol table info available.
>  #11 0x00005636e0560356 in PyEval_EvalFrameEx ()
>  No symbol table info available.
>  #12 0x00005636e0568927 in PyEval_EvalCodeEx ()
>  No symbol table info available.
>  #13 0x00005636e05111b3 in ?? ()
>  No symbol table info available.
>  #14 0x00005636e05f72f7 in PyObject_Call ()
>  No symbol table info available.
>  #15 0x00005636e052cc0e in ?? ()
>  No symbol table info available.
>  #16 0x00005636e05f72f7 in PyObject_Call ()
>  No symbol table info available.
>  #17 0x00005636e05b71e9 in ?? ()
>  No symbol table info available.
>  #18 0x00005636e05be6b4 in ?? ()
>  No symbol table info available.
>  #19 0x00005636e05f72f7 in PyObject_Call ()
>  No symbol table info available.
>  #20 0x00005636e0562f01 in PyEval_EvalFrameEx ()
>  No symbol table info available.
>  #21 0x00005636e05673f6 in ?? ()
>  No symbol table info available.
>  #22 0x00005636e05680af in PyEval_EvalCode ()
>  No symbol table info available.
>  #23 0x00005636e0641532 in ?? ()
>  No symbol table info available.
>  #24 0x00005636e0495956 in PyRun_InteractiveOneObject ()
>  No symbol table info available.
>  #25 0x00005636e0495aff in PyRun_InteractiveLoopFlags ()
>  No symbol table info available.
>  #26 0x00005636e06442f4 in PyRun_AnyFileExFlags ()
>  No symbol table info available.
>  #27 0x00005636e0503bff in ?? ()
>  No symbol table info available.
>  #28 0x00005636e05047e1 in main ()
>  No symbol table info available.

**Comment by twdkeule** [comment]
It seems the issue in in the iperf3 library?

**Comment by thiezn** [comment]
Hi @twdkeule, I can't seem to reproduce this issue but it's hard to troubleshoot without seeing the exact script you were running. The IPerf3.Server object does make use of threads to be able to still capture Ctrl+C whilst running so that might be causing some issues in combination with your use of the library?

If you need any assistance please create a new issue, including a bit more detail on what you're trying to do.

**Comment by twdkeule** [comment]
Yeah, I'm not sure anymore what I was doing. Thanks anyway!
