### ISSUE TITLE
"bandwidth" attribute

### ISSUE THREAD

**Issue by Dron-Z** [thiezn/iperf3-python#21]
I'm using iperf3 for testing VoIP quality, and would like to use iperf-lib, but can't set bandwidth in udp mode, script tests at the maximum speed that it can send.
for example:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import iperf3

client = iperf3.Client()
client.protocol = 'udp'
client.bandwidth = 1
client.duration = 5
client.server_hostname = '127.0.0.1'
client.port = 6969

result = client.run()

print('')
print('Test completed:')
print('  started at         {0}'.format(result.time))
print('  bytes transmitted  {0}'.format(result.bytes))
print('  jitter (ms)        {0}'.format(result.jitter_ms))
print('  avg cpu load       {0}%\n'.format(result.local_cpu_total))
print('  Megabits per second  (Mbps)  {0}'.format(result.Mbps))
```
where out are:
```dronz@vm-debian8-asterisk:/home/dronz/nauMon# ./nauMon.py 

Test completed:
  started at         Sun, 25 Jun 2017 04:26:54 GMT
  bytes transmitted  21561039487
  jitter (ms)        0.00436181
  avg cpu load       87.6748%

  Megabits per second  (Mbps)  32899.4750977
```

In CLI version iperf work is fine

Debian GNU/Linux 8.8 (jessie)
Python 2.7.9

**Comment by b12mihai** [comment]
I am having the same issue. Bandwidth setting is just not taken into account. Not sure though it's an actual issue in iperf3 API instead of this python lib. 

Did somebody take a look into this?

**Comment by thiezn** [comment]
Hi @ChristofKaufmann

My intention is to follow the libiperf3 library as closely as possible which is why the default value of the library is used. If the libiperf3 defaults get updated, iperf3-python should follow automatically.

@Dron-Z can you confirm this is working for you, taking into account the bandwidth parameter is in bits/second?

**Comment by ChristofKaufmann** [comment]
@thiezn That's reasonable, but from the user perspective it would be nice to have quick access to the default settings as if using the CLI. Because now it is easy to make mistakes, when not aware of the source code of the CLI.

**Comment by Dron-Z** [comment]
> Hi @ChristofKaufmann
> 
> My intention is to follow the libiperf3 library as closely as possible which is why the default value of the library is used. If the libiperf3 defaults get updated, iperf3-python should follow automatically.
> 
> @Dron-Z can you confirm this is working for you, taking into account the bandwidth parameter is in bits/second?

Yes, it's works. I'm don't know why I'm didn't check this format before ) Thnx
