### ISSUE TITLE
Could not find shared library libiperf.so.0 (on OSX)

### ISSUE THREAD

**Issue by jmack51** [thiezn/iperf3-python#23]
This is a great wrapper and I'd love to use it on my Mac Book Pro (OSX Sierra 10.12.16).  Are there any workarounds/fixes for the fatal error on OSX where it can't find libiperf.so.0 ?

**Comment by thiezn** [comment]
@jmack51 Thanks to @Austinpayne this should now work in the latest release on PyPi.
