### ISSUE TITLE
iperf3 segmentation fault in python

### ISSUE THREAD

**Issue by gabby33** [thiezn/iperf3-python#27]
I am trying to write a python code for iperf3 on a virtual machine with ubuntu 14.04 installed. Anytime i run this command "client = iperf3.Client()" i get a segmentation fault(core dumped) error.
Any help with how to solve this problem.

**Comment by thiezn** [comment]
Hi @gabby33, I've just pushed a new release, v0.1.8 to PyPi. Can you check if this resolves your issue?

**Comment by gabby33** [comment]
Hi @thiezn my problem has been resolved. Thanks

**Comment by thiezn** [comment]
Thanks for checking!
