### ISSUE TITLE
"bulksize" parameter 

### ISSUE THREAD

**Issue by cvicente** [thiezn/iperf3-python#9]
I wondered what "bulksize" was referring to. A quick glance at the iperf3 code seems to indicate that it actually corresponds to the "-l, --len" parameter in the CLI:

https://github.com/esnet/iperf/blob/a5f5765c8c9f7d3b8b7818addd8ed81a8adee9f5/src/iperf.h#L112

Perhaps "bulksize" should be renamed?

**Comment by fciaccia** [comment]
As you pointed out the API calls it *bulksize* and even if I agree that the name is not fully intuitive I think being this package a wrapper for libiperf we should stick to their nomenclature.

**Comment by cvicente** [comment]
Notice that the API uses "blksize", not "bulksize" (no "u"). That was my
point.

On Wed, Sep 28, 2016 at 8:23 AM, Francesco Ciaccia <notifications@github.com

**Comment by fciaccia** [comment]
Sorry, thought you wanted to change it to something like *lenght* as the CLI option. In that case I agree with you.

**Comment by thiezn** [comment]
you're right @cvicente, I'll add blksize to be consistent with the libiperf API in the next release. i'll keep bulksize for now as well for backwards compatibility. 

A bit swamped at the moment but hope to get another release out in the weekend

**Comment by thiezn** [comment]
better late than never I'd say...?! Release v0.1.8 (https://github.com/thiezn/iperf3-python/commit/2a6b7f1e24eeda49ba427f6029d7260f27e32b69) adds the blksize argument. I've kept bulksize as an available option to ensure backwards compatibility.
